# Materials file
[[materials]]
name = "default"
id = 0
color = [1.0, 0.0, 1.0, 1.0]
diggable = false
passable = false
alt = 0

[[materials]]
name = "air"
template = "default"
id = 1
color = [0.21, 0.54, 0.84, 1.0]
passable = true

[[materials]]
name = "stone"
template = "default"
id = 2
color = [0.44, 0.49, 0.57, 1.0]
diggable = true
alt = 6

[[materials]]
name = "dirt"
template = "default"
id = 3
color = [0.37, 0.31, 0.12, 1.0]
diggable = true

[[materials]]
name = "sand"
template = "default"
id = 4
color = [0.88, 0.87, 0.63, 1.0]
diggable = true

[[materials]]
name = "grass"
template = "default"
id = 5
color = [0.10, 0.65, 0.07, 1.0]
diggable = true
alt = 7  # Hack to implement digging. Remove once better serialization for maps supported

[[materials]]
name = "stone_floor"
template = "stone"
id = 6
color = [0.54, 0.59, 0.67, 1.0]
diggable = false
passable = true

[[materials]]
name = "grass_floor"
template = "grass"
id = 7
diggable = false
passable = true

[[materials]]
name = "upstairs"
template = "default"
id = 8
color = [0.39, 0.39, 0.39, 1.0]
passable = true

[[materials]]
name = "downstairs"
template = "default"
id = 9
color = [0.39, 0.39, 0.39, 1.0]
passable = true
