[[creatures]]
name = "default"
id = 0
texture = ""
dig_speed = 300
movement_speed = 30
color = [1.0,1.0,1.0,1.0]
alt = 0

[[creatures]]
name = "dwarf"
id = 1
template = "default"
color = [0.9,0.1,0.1,1.0]

[[creatures]]
name = "dog"
id = 2
template = "default"
color = [0.1,0.9,0.1,1.0]

[[creatures]]
name = "troll"
id = 3
template = "default"
color = [0.1,0.1,0.9,1.0]
