[[creatures]]
name = "default"
id = 0
color = [255,255,255,255]

[[creatures]]
name = "dwarf"
id = 1
color = [240,30,30,255]

[[creatures]]
name = "dog"
id = 2
color = [30,240,30,255]

[[creatures]]
name = "troll"
id = 3
color = [30,30,240,255]
